GeradorDeRotas/Controllers/EquipesController.cs
using System.Linq;
using System.Threading.Tasks;
using GeradorDeRotas.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace GeradorDeRotas.Controllers
{
    public class EquipesController : Controller
    {
        private readonly EquipeService _equipeService;
        private readonly PessoaService _pessoaService;
        private readonly ExcelService _excelService;
        public EquipesController(
            EquipeService equipeService,
            PessoaService pessoaService,
            ExcelService excelService)
        {
            _equipeService = equipeService;
            _pessoaService = pessoaService;
            _excelService = excelService;
        }

        // GET: EquipesController
        [Authorize]
        public async Task<ActionResult> Index() => View(await _equipeService.Get());

        // GET: EquipesController/Details/5
        [Authorize]
        public async Task<ActionResult> Details(string id) => View(await _equipeService.Get(id));

        // GET: EquipesController/Create
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var pessoas = await _pessoaService.GetDisponivel();
            ViewBag.Pessoas = new MultiSelectList(pessoas, "Cpf", "Nome");
            var excel = _excelService.Get();

            if (excel == null)
			{
                TempData["necessarioExportar"] = "Falha";
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Cidades = new SelectList(_excelService.GetCidades());

            return View();
        }

        // POST: EquipesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create(Equipe equipe)
        {
            try
            {
                if (!equipe.Valida)
                {
                    TempData["equipeInvalida"] = "equipe inválida.";
                    return RedirectToAction(nameof(Create));
                }

                foreach (var cpf in equipe.Cpfs)
                {
                    var pessoa = await _pessoaService.GetByCpf(cpf);
                    equipe.Pessoas.Add(pessoa);
                    pessoa.Disponivel = false;
                    await _pessoaService.Update(pessoa.Id, pessoa);
                }

                TempData["equipeSucesso"] = "Equipe criada com sucesso!";

                await _equipeService.Create(equipe);
                return RedirectToAction(nameof(Create));
            }
            catch
            {
                return View();
            }
        }

        // GET: EquipesController/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(string id)
        {
            ViewBag.Cidades = new SelectList(_excelService.GetCidades());

            var equipe = await _equipeService.Get(id);
            if (equipe == null)
                return NotFound("Equipe não encontrada!");
            return View(equipe);
        }

        // POST: EquipesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(string id, Equipe equipe)
        {
            try
            {
                if (!equipe.EditarValido)
                {
                    TempData["equipeInvalida"] = "equipe inválida.";
                    return RedirectToAction(nameof(Edit));
                }

                var equipeResponse = await _equipeService.Get(id);
                equipeResponse.AlterarCidadeNome(equipe.NomeEquipe, equipe.Cidade);

                await _equipeService.Update(id, equipeResponse);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: EquipesController/Delete/5
        [HttpDelete]
        [Authorize]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                var equipe = await _equipeService.Get(id);
                foreach (var pessoa in equipe.Pessoas)
                {
                    pessoa.Disponivel = true;
                    await _pessoaService.Update(pessoa.Id, pessoa);
                }

                await _equipeService.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

GeradorDeRotas/Controllers/ExcelController.cs
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using ClosedXML.Excel;
using GeradorDeRotas.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using Newtonsoft.Json;

namespace GeradorDeRotas.Controllers
{
    public class ExcelController : Controller
    {
        private readonly ExcelService _excelService;
        private readonly string[] _extensoesPermitidas = { ".xlsx", ".xls" };
        public ExcelController(ExcelService testeService)
        {
            _excelService = testeService;
        }

        [HttpPost]
        [Authorize]
        public IActionResult Index()
        {
            var files = HttpContext.Request.Form.Files;

            if (!files.Any() || !_extensoesPermitidas.Contains(Path.GetExtension(files[0].FileName).ToLowerInvariant()))
            {
                TempData["arquivoInvalido"] = "Nenhum arquivo selecionado!";
                return RedirectToAction(nameof(Upload));
            }

            var xls = new XLWorkbook(files[0].OpenReadStream());
            var planilha = xls.Worksheets.First();

            var columns = new List<string>();
            var qtdColumns = planilha.Columns().Count();

            var dt = new DataTable();

            for (int i = 1; i < qtdColumns; i++)
            {
                var col = planilha.Column(i).FirstCell().Value.ToString();
                dt.Columns.Add(col);
                columns.Add(col);
            }

            var linha = 2;
            var continuar = true;

            while (continuar)
            {
                var d = new string[columns.Count()];
                int index = 0;
                for (int i = 1; i <= columns.Count(); i++)
                {
                    d[index] = planilha.Column(i).Cell(linha).Value.ToString();
                    index++;
                }

                continuar = d.Any(x => !string.IsNullOrEmpty(x));

                if (continuar) dt.Rows.Add(d);

                linha++;
            }


            dt.DefaultView.Sort = "cep ASC";
            dt = dt.DefaultView.ToTable();

            var excel = new Excel();

            for (int i = 1; i < dt.Rows.Count - 1; i++)
            {
                var dictionary = new Dictionary<string, string>();
                int j = 0;
                foreach (var item in columns)
                {
                    dictionary.Add(item, dt.Rows[i][j].ToString());
                    j++;
                }
                var json = JsonConvert.SerializeObject(dictionary);
                var document = BsonSerializer.Deserialize<BsonDocument>(json);
                excel.ArquivosExcel.Add(document);
            }

            _excelService.Remove();
            _excelService.Create(excel);

            TempData["arquivoSucesso"] = "Sucesso";

            return RedirectToAction(nameof(Upload));
        }

        [Authorize]
        public IActionResult Upload()
        {
            return View();
        }
    }
}

GeradorDeRotas/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GeradorDeRotas.Models;
using GeradorDeRotas.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using Xceed.Words.NET;

namespace GeradorDeRotas.Controllers
{
    public class WordController : Controller
    {
        private readonly EquipeService _equipeService;
        private readonly ExcelService _excelService;
        public WordController(
            EquipeService equipeService,
            ExcelService excelService)
        {
            _equipeService = equipeService;
            _excelService = excelService;
        }

        [Authorize]
        public ActionResult Export()
        {
            var rotas = new List<string>();

            var excel = _excelService.Get();

            if (excel == null)
            {
                TempData["necessarioExportar"] = "Falha!";
                ViewBag.Rotas = new SelectList(new List<string>());
                ViewBag.Servicos = new SelectList(new List<string>());
                ViewBag.Cidades = new SelectList(new List<string>());
                ViewBag.Equipes = new MultiSelectList(new List<string>(), "Id", "NomeEquipe");
                return View();
            }

            foreach (var item in excel.ArquivosExcel.First())
                rotas.Add(item.Name);

            rotas.RemoveAll(x => x == "CONTRATO" || x == "ASSINANTE" || x == "ENDEREÇO" || x == "CEP" || x == "OS" || x == "TIPO OS");

            ViewBag.Rotas = new SelectList(rotas);
            ViewBag.Servicos = new SelectList(_excelService.GetServicos());
            ViewBag.Cidades = new SelectList(new List<string>());
            ViewBag.Equipes = new MultiSelectList(new List<string>(), "Id", "NomeEquipe");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Export(Word word)
        {
            try
            {
                if (word.Servico == null)
                {
                    TempData["semServico"] = "Nenhum serviço selecionado.";
                    return RedirectToAction(nameof(Export));
                }

                var stream = new MemoryStream();
                var doc = DocX.Create(stream);

                var paragrafo = doc.InsertParagraph();
                paragrafo.Append($"ROTA TRABALHO - {DateTime.Now:d}").Font("Times New Roman").FontSize(18).Bold().Alignment = Xceed.Document.NET.Alignment.center;

                paragrafo = doc.InsertParagraph();
                paragrafo.Append("RETORNOS").Font("Times New Roman").FontSize(15).Bold().Alignment = Xceed.Document.NET.Alignment.center;


                var excel = _excelService.Get();
                excel.ArquivosExcel.RemoveAll(x => x.GetValue("SERVIÇO") != word.Servico);

                var equipes = new List<Equipe>();

                foreach (var equipeId in word.EquipeIds)
                    equipes.Add(await _equipeService.Get(equipeId));

                var dadosEquipe = excel.ArquivosExcel.FindAll(x => x.GetValue("CIDADE") == word.Cidade).OrderBy(x => x.GetValue("CEP"));

                var qtdServicosEquipe = Math.Floor((double)dadosEquipe.Count() / equipes.Count);
                var resto = dadosEquipe.Count() % equipes.Count;

                var indice = 0;
                var indiceEquipe = 0;

                foreach (var dadoEquipe in dadosEquipe)
                {
                    if (qtdServicosEquipe <= 0 || (resto > 0 && indice == qtdServicosEquipe + 1) || (resto == 0 && indice == qtdServicosEquipe))
                    {
                        indiceEquipe++;
                        indice = 0;
                    }

                    var equipe = equipes[indiceEquipe];

                    if (indice == 0)
                    {
                        paragrafo = doc.InsertParagraph();
                        paragrafo = doc.InsertParagraph();
                        paragrafo = doc.InsertParagraph();
                        paragrafo = doc.InsertParagraph();
                        paragrafo.Append($"Nome da Equipe: {equipe.NomeEquipe}").Font("Times New Roman").FontSize(15).Bold();
                    }

                    paragrafo = doc.InsertParagraph();
                    paragrafo = doc.InsertParagraph();
                    dadoEquipe.TryGetValue("CONTRATO", out var contrato);
                    dadoEquipe.TryGetValue("ASSINANTE", out var assinante);
                    dadoEquipe.TryGetValue("PERÍODO", out var periodo);
                    paragrafo.Append($"Contrato: {contrato}  -  Assinante: {assinante}  -  Período: {periodo}").Font("Times New Roman").FontSize(14).Bold().UnderlineStyle(Xceed.Document.NET.UnderlineStyle.singleLine);

                    paragrafo = doc.InsertParagraph();
                    paragrafo.Append($"Endereço: {dadoEquipe.GetValue("ENDEREÇO")} - {dadoEquipe.GetValue("CEP")}").Font("Times New Roman").FontSize(14);

                    paragrafo = doc.InsertParagraph();
                    paragrafo.Append($"O.S: {dadoEquipe.GetValue("OS")}  -  ").Font("Times New Roman").FontSize(14);
                    paragrafo.Append($"TIPO O.S: {dadoEquipe.GetValue("TIPO OS")}").Font("Times New Roman").FontSize(14).Color(Color.White).Highlight(Xceed.Document.NET.Highlight.red);

                    foreach (var rota in word.Rotas)
                    {
                        paragrafo = doc.InsertParagraph();
                        paragrafo.Append($"{rota[0] + rota[1..].ToLower()}: {dadoEquipe.GetValue(rota)}").Font("Times New Roman").FontSize(14);
                    }

                    indice++;
                }

                doc.Save();

                TempData["exportarSucesso"] = "Sucesso!";

                return File(stream.ToArray(), "application/octet-stream", "Rotas.docx");
            }
            catch
            {
                return RedirectToAction(nameof(Export));
            }
        }
    }
}

GeradorDeRotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Gerador de Rotas</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/lib/chosen/dist/css/chosen.min.css" />
	<link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerador de Rotas</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Equipes" asp-action="Index">Equipes</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Excel" asp-action="Upload">Importar</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Word" asp-action="Export">Exportar</a>
						</li>

						@if (User.Identity.IsAuthenticated)
						{

							<li style="margin-left: 450px" class="nav-item">
								<a style="pointer-events: none" class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Olá, @User.Identity.Name!</a>
							</li>
							@*<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
								</li>*@
							<a asp-area="" asp-controller="Usuarios" asp-action="Logout" class="nav-link material-symbols-outlined">
								logout
							</a>
						}
						@if (!User.Identity.IsAuthenticated)
						{
							<li style="margin-left: 500px" class="nav-item">
								<a asp-area="" asp-controller="Usuarios" asp-action="Login" class="nav-link text-dark material-symbols-outlined">
									login
								</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Gerador de Rotas
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/chosen/dist/js/chosen.jquery.min.js"></script>
	<script src="~/js/multiSelect.js"></script>
	<script src="~/lib/jQuery-Mask-Plugin/src/jquery.mask.js" type="text/javascript" asp-append-version="true"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>